spring:
  application:
    name: GatewayService
  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:10001/}
management:
  endpoints:
    enabled-by-default: false