server:
  port: 10001
spring:
  application:
    name: ConfigService
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
  profiles:
    active: native